policies:
- action: '*'
  effect: allow
  object: '*'
  subject: admin
- action: read
  effect: allow
  object: '*'
  subject: manager
- action: create
  effect: allow
  object: document
  subject: manager
- action: update
  effect: allow
  object: document
  subject: manager
- action: create
  effect: allow
  object: project
  subject: manager
- action: update
  effect: allow
  object: project
  subject: manager
- action: create
  effect: allow
  object: task
  subject: manager
- action: read
  effect: allow
  object: document
  subject: editor
- action: create
  effect: allow
  object: document
  subject: editor
- action: update
  effect: allow
  object: document
  subject: editor
- action: read
  effect: allow
  object: task
  subject: editor
- action: create
  effect: allow
  object: task
  subject: editor
- action: update
  effect: allow
  object: task
  subject: editor
- action: read
  effect: allow
  object: document
  subject: viewer
- action: read
  effect: allow
  object: project
  subject: viewer
- action: read
  effect: allow
  object: task
  subject: viewer
